import {gql} from '@apollo/client'

export const GET_ALL_LOCATION = gql`
query{
    allAffectedLocations{
      id
      affectedLocationName
      village
      commune
      district
      province
      other
      open
      openAt
      closeAt
      personalInfo{
        id
        firstName
        lastName
        gender
        village
        commune
        district
        province
      }
      case{
        id
        caseName
        village
        commune
        district
        province
        other
        date
        long
        lat
      }
      long
      lat
      coorporate
      infected
    }
  }
`;

export const CREATE_NEW_LOCATION = gql`
mutation createAffectedLocation(
  $affectedLocationName:String,
  $village:String,
  $commune:String,
  $district:String,
  $province:String,
  $other:String,
  $case:ID!,
  $long:Float,
  $lat:Float,
  $personalInfo:ID!
){
  createAffectedLocation(newAffectedLocation:{
		affectedLocationName:$affectedLocationName
    village:$village
    commune:$commune
    district:$district
    province:$province
    other:$other
    case:$case
    long:$long
    lat:$lat
    personalInfo:$personalInfo
  }){
    message
    success
  }
}
`;